### ISSUE TITLE
What is the meaning of events 0 and 1? can you please add this to the docs or point me to the relevant information?

### ISSUE THREAD

**Issue by Veghit** [loft-br/xgboost-survival-embeddings#34]
### Instructions
- Delete everything between parenthesis _(...)_
- Remove the sections that are not relevant

### Describe the documentation issue
_(explain more about the issue you found, if it's a missing doc or a improvement)_

**Comment by GabrielGimenez** [comment]
We still don't have documentation that explains survival analysis

Survival analysis tries to model the time until an event, given that the event might not occur or we don't have information about the subject after certain time. 

To do that we need two target variables, `event`, where `event == 1` means that an event occurred and `event == 0` means that for the current time, it didn't occur. And `time`, that indicates how much time it took for the event to happen if `event == 1` or indicates how much time we observed the subject if `event == 0`

You can also use `event == True` or `event == False` instead of 1 and 0
