### ISSUE TITLE
risk_score  and  data

### ISSUE THREAD

**Issue by Smile-L-up** [loft-br/xgboost-survival-embeddings#45]
您好，感谢您分享这么优秀的工作。我想请教一下，这个模型可以单独输出类似与cox具有的risk_score吗？
此外借助下面两行代码加载数据加载不了，希望您能够上传一部分案例数据，作为参考学习。
from pycox.datasets import metabric
df = metabric.read_df()

**Comment by GabrielGimenez** [comment]
Hello! If you need risk scores you can pass the  `return_interval_probs=True` on predictions and you'll get a risk score for each time window used. Something like this: `model.predict(X, return_interval_probs=False)`

About the data, you have to install the pycox library independently, we didn't at it as a dependency because it depends on pytorch and it would be a very large dependency and a harder install
